---
title: "經濟學人一週大事_政治篇"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext);library(sf);library(maps);library(plotly);library(rmapshaper);library(leaflet);library(osmdata);library(magick);library(scales);library(rvest)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', echo=FALSE, fig.showtext=T)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Worldmap
<div id=Worldmap>
```{r}
source("https://www.dropbox.com/s/4tubw8e5h3cem6w/theEconomist.R?dl=1")

"https://www.economist.com/the-world-this-week/2019/11/21/politics-this-week" %>%
  get_theWorldThisWeek() -> df_politics
graphData <-list()
graphData$df_politics <- df_politics
countries<-c("America","South Korea","Britain","BurkinaFaso","Mali","Niger","Chile","Syria","Iran","Israel","Belarus","HongKong","Sweden","SriLanka","Bolivia","Brazil","Afghanistan")
values <-rnorm(17)
map<-cbind(countries,values)
map<-as.data.frame(map)
graphData$map <-map
world <- map_data('world')
world <- world %>% filter(region != "Antarctica")
graphData$map %>%
  ggplot()+
  geom_map(data=world, map=world,
                  aes(x=long, y=lat, group=group, map_id=region),
                  fill="white", colour="black") + 
  geom_map(data=graphData$map, map=world,
                  aes(fill=countries, map_id=countries),
                  colour="black")+
theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.line.x=element_blank(),
       axis.line.y=element_blank(),
      axis.text.y=element_blank(),
      axis.title.y=element_blank(),
      legend.position = "none")->worldgraph
worldgraph%>%plotly()

```
</div>
Column {data-width=350}
-----------------------------------------------------------------------

### News this week

```{r}

```

### Politics in the country 

```{r}

```

