---
title: "R Practice"
output: html_notebook
---
## list -> data.frame
```{r}
StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuList 
as.data.frame(StuList) -> StuDFfromList
StuDFfromList
```


```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
length(StuDF) # 從向量角度看
nrow(StuDF) # 從矩陣角度看
```

```{r}
library(dplyr)
str(StuDF)
head(StuDF)
tail(StuDF)
StuDF
slice(StuDF,1:3)
slice(StuDF,4:5)
slice(StuDF,n())
```


```{r}
slice(StuDF,(n()-1):n())
```

```{r}
StuDF
mutate(StuDF,
       調分後成績=成績+10)
transmute(StuDF,
       調分後成績=成績+10) # 不保留其他變數
```
##變數運算，前步驟出現的新變數，後步驟可直接拿來用。


```{r}
StuDF
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
StuDF$調分後成績 <-
  StuDF$成績+10
```

```{r}
StuDF
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績)) -> StuDF2
```
```{r}
StuDF2
names(StuDF2)
select(StuDF2,
       姓名,學號,成績,調分後成績)
select(StuDF2,
       -次序,-性別,-最高分,-最低分)
```
```{r}
select(StuDF2,
       次序,性別,
       contains("最"))

select(StuDF2,
       -次序,-性別,
       -contains("最"))
```

```{r}
StuDF
# logical vector
logiChoose <- c(
  F,F,F,T,T,F,T,F
)
# 使用logical vector選擇所要觀測值"女"
StuDF[logiChoose,]
```
##which()可顯示向量元素為真的位置。
```{r}
logiChoose
which(logiChoose)
slice(
  StuDF,which(logiChoose)
)
```

```{r}
StuDF$性別=="女" # logical predicate

logiChoose <- StuDF$性別=="女"
StuDF[logiChoose,]
```

```{r}
# relational operators
StuDF$性別=="女" 
StuDF$成績>60

# combined with logical operator
(StuDF$性別=="女" & StuDF$成績>60) -> logiChoose2
logiChoose2

StuDF[logiChoose2,]
```

```{r}
StuDF
filter(StuDF,
       性別=="女")
filter(StuDF,
       (性別=="女" & 成績>60))
filter(StuDF,
       性別=="女",
       成績>60) # 多個AND條件可用,分隔
```

```{r}
StuDF
filter(StuDF,
       性別=="女")%>%
  summarise(
    平均成績=mean(成績),
    最高分=max(成績),
    最低分=min(成績)
     )

```
```{r}
group_by(StuDF,
         性別,
         (成績>75)) -> StuDF_by性別成績

summarise(StuDF_by性別成績,
          平均成績=mean(成績),
          人數=n())
```

```{r}
group_by(StuDF,
         性別) -> StuDF_by性別

# 使用grouped data frame
summarise(StuDF_by性別,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

# 使用ungrouped data frame
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
mutate(
  StuDF_by性別,
  最高分=max(成績),
  最低分=min(成績),
  調分大小=(最高分-最低分)/5,
  調分後成績=成績+調分大小
) -> StuDF_依性別調分
StuDF_依性別調分
ungroup(StuDF_依性別調分) -> 
  StuDF_調分後
  StuDF_調分後
```
##gather()
##key->將原為column的數據轉成列的對應column名稱
##value-> 因將行轉成列所產生的值(就是原本在key的數據)的名稱
```{r}
library(tidyr)
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)
df_gatherExample
gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口")
```


```{r}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")

```

```{r}
df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朶萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))
```

##spread
高瘦矩陣->矮胖矩陣
spread(data, the name of the column contains the values you want to tranfer them into column name,對應值(原本在矩陣內的數據) )
```{r}
df_spreadExample
spread(df_spreadExample,
       var,value)
```
##str_replace(vector,"要換下的字眼","要換上的字眼")
```{r}
library(stringr)

fruits <- c("one apple", "two pears", "three bananas")
str_replace(fruits, "[aeiou]", "-")
str_replace_all(fruits, "[aeiou]", "-")
str_replace_all(fruits, "[aeiou]", toupper)
str_replace_all(fruits, "b", NA_character_)
```
```{r}
library(readr)
library(dplyr)
cl<-locale(grouping_mark = ",")
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")
collegeData %>%
  mutate_at(
    vars(
      contains("女")
    ),
    funs(
      parse_number(.,locale=cl,na=c("","NA","-"))
    )
  ) -> collegeData5
 collegeData5 %>% str
```

