---
title: "Untitled"
author: "陳盈蓁"
date: "2019/9/11"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_005.Rda?raw=true"))
c('area','age','性別','n')->names(graphdata[[1]])
## ----graph, echo=T, eval=T-----------------------------------------------
library(ggalluvial)
#is_alluvia_form(as.data.frame(graphdata), axes = 1:3, silent = TRUE)
                                          finalplot<-ggplot(as.data.frame(graphdata),
       aes(y = n, axis1 = age, axis2 =area)) +
  geom_alluvium(aes(fill=性別), width = 1/10) +
  geom_stratum(width = 1/10, fill = "gray", color = "white") +
  geom_label(stat = "stratum", label.strata = TRUE) +scale_x_discrete(limits = c("age", "area"), expand = c(.1, .1)) +scale_fill_brewer(type = "qual", palette = "Set2")+
ggtitle("2018年登革熱病例統計")+ylab('確診人數')+theme(title = element_text(family ="QYuan" ))
finalplot                                                                                           
```
##20191023課程內容
電子書4.1.3
```{r}
library(readr)
library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")
graphList <- list()
```





```{r}
library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102

library100_102 %>%
  filter(
    借閱日期 %>% between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=as.factor(讀者年級)
    )-> library2014 
```



```{r}
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T)
  ) -> library2014

library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```
##geom_bar with position="stack" 資料堆疊在同一長方形
```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7, position="stack"
  )
```
##geom_bar with position="dodge" 各項拆開 平行排列
```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7, position = "dodge"
  )
```
##geom_bar with position="fill" 百分比成份拆解
```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7, position="fill"
  )
```


```{r}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院) # 預設 stat="count"
  )
```

```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院), 
    geom="bar" # geom_bar內訂會取 count來當y
  )
```
```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop)), 
    geom="bar" # geom_bar內訂會取 count來當y
  )
```


##設定大家同group
```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop)), group="全校")

       stat_count(
      aes(x=學院,y=stat(prop)),group="全校",label=stat(group),
     geom="text")
```


```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院)
  )+
  stat_count(
    aes(x=學院,y=stat(count),label=stat(count)), geom="text"
  )
```

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop))
  )+
  stat_count(
    aes(x=學院,y=stat(prop),label=stat(prop)), geom="text"
  )
```

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") 
  )+
  stat_count(
    aes(
      x=學院,
      y=stat(prop), group="全校",
      label=round(stat(prop),digits=2)),
    geom="text",
    color="white", nudge_y=-0.01
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )
```

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") 
  )+
  geom_text(
    aes(
      x=學院,
      y=stat(prop), group="全校",
      label=round(stat(prop),digits=2)),
    stat="count",
    color="white",nudge_y=-0.01
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )
```

##stat_function
```{r}
df_x <- data.frame(
  x=rnorm(500,mean=2,sd=1)
)
df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(
    aes(y=stat(density))
  )+
  stat_function(
    fun=dnorm, args = list(mean=2, sd=1) # dnorm 為常態分配density函數
  )
```

```{r}
market_demand <- function(x, a=1, b=-1){
  return(a+b*x)
}

market_supply <- function(x, a=0, b=1){
  return(a+b*x)
}

df_grids <- 
  data.frame(
    x=seq(0,1,by=0.2))

df_grids %>%
  ggplot(aes(x=x))+
  stat_function(
    fun="market_demand"
  )+
  stat_function(
    fun="market_supply"
  )+
  stat_function(
    fun="market_supply",
    args = list(b=0.8),color="red"
  )+
  scale_y_continuous(
    limits = c(0,1)
  )+
  labs(
    x="Quantity", y="Price"
  ) -> graphList$demand_supply

graphList$demand_supply
```

```{r}
graphList$demand_supply+
  stat_function(
    fun="market_demand",
    args=list(b=-2), color='red'
  )
```

```{r}
graphList$demand_supply+
  geom_ribbon(
    data=data.frame(
      x=seq(0.25,0.5,by=0.01)
    ),
    aes(y=x),
    stat="summary", 
    fun.ymin= function(y) market_demand(y),
    fun.ymax= function(y) market_supply(y),
    alpha=0.3
  )
```

```{r}
df0 <-
  data.frame(
    x=seq(0.25,0.5,by=0.01),
    y=seq(0.25,0.5,by=0.01)
  )
```

