---
title: "Untitled"
author: "陳盈蓁"
date: "2019/9/11"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework2/graphData_homework2_005.Rda?raw=true"))
## ----graph, echo=T, eval=T-----------------------------------------------
graphData$data %>%
  ggplot(aes(x=年份,y=毛額,color=國民所得_儲蓄_投資毛額))+
  geom_line(aes(linetype=國民所得_儲蓄_投資毛額,size=國民所得_儲蓄_投資毛額))+
  
  scale_linetype_manual(
    values = c("85","12","31"),
    breaks = c(
    "1.4國民所得毛額GNI:1.1+1.2+1.3","3.3國民儲蓄毛額 :2.1+3.2","3.5國內投資毛額"),
    labels = c("所得毛額","儲蓄毛額","投資毛額")
    )+
  theme(legend.position = "none")+
  scale_size_manual(values = c(1,0.5,0.2))+
  
  annotate("text", x = 2016, y = 155000, 
           label = paste("國民所得毛額"), size = 3)+
  annotate("text", x = 2016, y = 70000, 
           label = paste("國民儲蓄毛額"), size = 3) +
  annotate("text", x = 2016, y = 42000, 
           label = paste("國民投資毛額"), size = 3) +
  annotate("text", x = 2010, y = 180000, 
           label = paste("2009年"), size = 3) +
  labs(title = "國民所得、儲蓄、投資毛額",
       caption = "資料來源: 中華民國統計資料網",
       tag = "單位:億(新台幣)")+
  
  geom_vline(aes(xintercept = 2009),linetype="dotted")
```
```{r}
graphData$events <- data.frame(
      xmin=c(2008, 2013),
      xmax=c(2009, 2014),
      ymin=c(rep(-Inf,2)),
      ymax=c(rep(Inf,2)),
      name=c("2008次貸危機","2013歐債危機")
    )
graphData$data %>%
  ggplot()+
  geom_line(aes(x=年份,y=毛額,color=國民所得_儲蓄_投資毛額,linetype=國民所得_儲蓄_投資毛額))+
  geom_rect(
    data=graphData$events,
    mapping=aes(
      xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax
    ),
    alpha=0.1
  ) +
  geom_text(
    data=graphData$events,
    aes(x=(xmin+xmax)/2,y=180000,label=name)
  )
```

```{r}


```

```{r}
library(readr)
library100_102 <- read_csv("https://www.dropbox.com/s/wuo5o6l55lk68l6/library100_102.csv?dl=1")
graphList<-list()
```
```{r}
library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102

library100_102 %>%
  filter(
    借閱日期 %>% between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=as.factor(讀者年級)
    )-> library2014 
```



```{r}
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T)
  ) -> library2014

library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```
##geom_bar with position="stack" 資料堆疊在同一長方形
```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7, position="stack"
  )
```
##geom_bar with position="dodge" 各項拆開 平行排列
```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7, position = "dodge"
  )
```
##geom_bar with position="fill" 百分比成份拆解
```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7, position="fill"
  )
```
##連續變數
```{r}
set.seed(2019)
x <- rnorm(100)
head(x)
```

```{r}
ggplot2::cut_interval(x,n=8) -> x_interval
levels(x_interval)
```

```{r}
head(x_interval)
```

```{r}
df_x <- data.frame(
  x=x,
  x_interval=x_interval
)

df_x %>%
  group_by(x_interval) %>%
  summarise(
    interval_count=n()
  ) %>%
  ungroup() %>% #View
  ggplot(aes(x=x_interval))+
  geom_col(
    aes(y=interval_count)
  )
```
```{r}
df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(bins=8)
```

```{r}
```

