---
title: "課堂練習20191030"
author: "陳盈蓁"
date: "2019/9/11"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
d <- ggplot(mtcars, aes(cyl, mpg)) + geom_point()
d + stat_summary(fun.y = "median", colour = "red", size = 2, geom = "point")
```

```{r}
```


```{r}
graphList <-list()
df_position <- data.frame(
  x=rep(c("a","b"), each=3),
  y=c(3,1,3,8,6,10)
)

df_position %>%
  ggplot(aes(x=x,y=y))+
  geom_point(
    color="#5A99B3"
  ) + 
  scale_y_continuous(
    breaks=c(1,3,6,8,10)
  )+
  annotate(
    geom="text",
    x=1.1, y=3, label="x 2" # 利用factor的type為integer的特質設x位置
  )+
  labs(
    title="Position identity",
    subtitle="Position沒有調整"
    ) -> graphList$position_none

df_position %>%
  ggplot(aes(x=x,y=y,color=y))+
  geom_point(
    position="stack", color="#5A99B3"
  )+
  labs(
    title= "Position stack",
    subtitle = "各x類y值疊加上去" 
  )-> graphList$position_stack

ggpubr::ggarrange(
  graphList$position_none,
  graphList$position_stack
)
```
no
```{r}
library(readr)
library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")
```

```{r}
library2014 %>%mutate(
  讀者年級=as.factor(讀者年級)
) ->library2014

library2014 %>%
  ggplot(aes(x=學院,fill=讀者年級)) -> graphList$圖書_ggplotOnly_with_aes

graphList$圖書_ggplotOnly_with_aes +
  geom_bar() # 內定position="stack"
```

```{r}
graphList$圖書_ggplotOnly_with_aes +
  geom_bar(
    width=0.7, position = "dodge"
  ) -> # fill類別較少的,width會放大
  graphList$圖書_positionDodge

graphList$圖書_positionDodge
```

```{r}
graphList$圖書_ggplotOnly_with_aes +
  geom_bar(
    width=0.7,
    position=position_dodge(width=0.8,preserve = "single") # 0.7寬，0.8dodge創造0.1間隔
  ) ->
  graphList$圖書_positionDodge_preserve

graphList$圖書_positionDodge_preserve
```

```{r}
graphList$圖書_ggplotOnly_with_aes +
  geom_bar(
    width=0.7,
    position=position_dodge(width=0.8,preserve = "single") # 0.7寬，0.8dodge創造0.1間隔
  ) ->
  graphList$圖書_positionDodge_preserve

graphList$圖書_positionDodge_preserve
```

```{r}
library2014 %>%
  select(學院,讀者年級) %>%
  arrange(學院,讀者年級) %>%
  group_by(學院,讀者年級) %>%
  summarise(
    count=n()
  ) %>% ungroup() %>%
  add_row(
    學院=c("電機資訊學院","法律學院"),
    讀者年級=c(1,1),
    count=c(0,0)
  ) -> library2014count

library2014count %>%
  ggplot(aes(x=學院,fill=讀者年級)) -> graphList$圖書_ggplotOnly_with_aes2

graphList$圖書_ggplotOnly_with_aes2 +
  geom_bar(
    aes(y=count), ##### 指定高度y
    stat="identity", ##### 自行設定y時使用
    width=0.7,
    position=position_dodge(width=0.8) # 0.7寬，0.8dodge創造0.1間隔, preserve = "single"在類別齊全時可不用
  ) ->
  graphList$圖書_positionDodge2

graphList$圖書_positionDodge2
```


```{r}
graphList$圖書_ggplotOnly_with_aes2 +
  geom_bar(
    stat="identity",
    aes(y=count), width=0.7, position="stack"
  )
```

```{r}

```

