---
title: "2019-09-18"
author: "陳盈蓁"
date: "2019/9/18"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuList 
as.data.frame(StuList) -> StuDFfromList
StuDFfromList
```
```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF 
```


```{r}
class(StuDF)
typeof(StuDF)
```


```{r}
class(StuDFfromList)
typeof(StuDFfromList)
```


```{r}
length(StuDF) # 從向量角度看
nrow(StuDF) # 從矩陣角度看```
```
##dplyr
```{r}
library(dplyr)
```

##結構
```{r}
str(StuDF)
```
##前六筆資料
```{r}
head(StuDF)
```

##後六筆資料
```{r}
tail(StuDF)
```
```{r}
StuDF
slice(StuDF,1:3)
slice(StuDF,4:5)
slice(StuDF,n()) ##n()總筆數
```
##最後兩筆資料
```{r}
slice(StuDF,(n()-1):n())
```
##第五到第七筆資料刪除
```{r}
StuDF
slice(StuDF,-5:-7)
slice(StuDF,-(5:7)) ##Better way 
```

```{r}
StuDF
slice(StuDF,c(1,4,8)) ##只要1,4,8筆資料
```
```{r}

```

