---
title: "2019-10-02"
author: "陳盈蓁"
date: "2019/10/02"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
library(grDevices) # 不同顏色模型代碼的呈現及轉換
library(scales) # show_col()螢幕立即顯示顏色
library(colorspace) # 調色盤選擇及ggplot應用工具
library(shinyjs) # 支援套件
```

```{r}
library(grDevices)
rgb(0,0,1) # 即對應顏色強度(0,0,255)
```

```{r}
library(scales)
show_col(c(rgb(0,0,1),rgb(0.5,0,0.7)))
```
```{r}
show_col(
  c(
    hsv(30/360,0,0),hsv(30/360,0.5,0),hsv(30/360,1,0), # (,,lightness=0) 全暗
    hsv(30/360,0,0.5),hsv(30/360,0.5,0.5),hsv(30/360,1,0.5), # (,,lightness=0.5)
    hsv(30/360,0,1),hsv(30/360,0.5,1),hsv(30/360,1,1) # (,,lightness=1) 全亮
  )
)
```
```{r}
ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) + geom_point() +
  scale_color_discrete_qualitative(palette = "Set 2")
```

```{r}
pal_qual <- qualitative_hcl(
  n = 7, 
  h = c(0, 360), c = 35, l = 85, 
  register = "myQualitative"
  )
pal_qual %>% specplot(hcl=F)
```
```{r}
pal_seq <- sequential_hcl(
  n = 7, 
  h = 135, c = c(45, NA, NA), l = c(35, 95), 
  power = 1.3, 
  register = "mySequential")
pal_seq %>% specplot(hcl=F)
```
```{r}
pal_diverge <- diverging_hcl(
  n = 7, 
  h = c(260, 0), c = 80, l = c(30, 90), 
  power = 1.5, 
  register = "myDiverge")
pal_diverge %>% specplot(hcl=F)
```

```{r}
data.frame(
  x1 = factor(sample(c(1L,2L,3L),100,replace=T)),
  x2 = runif(100),
  y = runif(100),
  z1 = rnorm(100),
  z2 = factor(sample(letters[1:4],100,replace=T))
) -> df_example
```

```{r}
df_example %>%
  ggplot()+
  geom_boxplot(
    aes(x=x1,y=y,fill=z2)
  ) -> basicBoxplot
basicBoxplot
```

```{r}
df_example %>%
  ggplot()+
  geom_point(
    aes(x=x2,y=y,color=z1)
  ) -> basicScatterPlot
basicScatterPlot
```

```{r}
basicBoxplot+
  scale_fill_brewer(palette = 1)
```
```{r}
basicScatterPlot +
  scale_color_continuous_sequential(palette = "mySequential")
```



```{r}
basicScatterPlot +
  scale_color_continuous_diverging(palette="myDiverge")
```

```{r}
sequential_hcl(n = 7, h = c(-4, 80), c = c(100, NA, 47), l = c(55, 96), power = c(1, NA), register = "myPalette11")
df_example %>%
  ggplot()+
  geom_point(
    aes(x=x2,y=y,color="z1")
  ) -> basicScatterPlot
basicScatterPlot+
```


```{r}
scale_color_discrete_sequential(palette = "myPalette11")
```

```{r}
iris
rename(iris, petal_length = Petal.Length)
```

